### ISSUE TITLE
Getting "policyViolations of undefined" when loading a python project with requirements.txt

### ISSUE THREAD

**Issue by roger-lau** [sonatype-nexus-community/vscode-iq-plugin#127]
<img width="448" alt="Screenshot 2020-10-15 at 15 12 59" src="https://user-images.githubusercontent.com/22045072/96090319-9c30f880-0efa-11eb-910a-7f613d8b3b0f.png">

Tried a few requirements.txt file, the error is consistent.

**Comment by hboutemy** [comment]
can you provide a sample `requirements.txt` file to easily reproduce the issue, please?

**Comment by hajimeo** [comment]
Not sure how to fix but just FYI, the error happens because componentEntry sometimes becomes 'undefined' in below line:
IqComponentModel.js
` 92                             componentEntry = this.coordsToComponent.get(componentContainer.PackageMuncher.ConvertToComponentEntry(resultEntry));`

**Comment by hboutemy** [comment]
perhaps known limitation: see #37

**Comment by hboutemy** [comment]
ok, I could reproduce the issue with following `requirements.txt`:
```
Werkzeug==0.16.0
Django==2.2.6
django-enumfields==1.0.0
django-admin-ip-restrictor==2.1.1
django-jsonfallback==2.1.2
django-storages==1.7.2
django-extensions==2.2.5
django-decorator-include==2.1
django-sequences==2.4
django-reversion==3.0.7
pytz==2019.3
python-dateutil==2.8.0
python-dotenv[cli]==0.10.3
requests==2.22.0
dpath==2.0.1
protobuf==3.10.0
```
