### ISSUE TITLE
[FEATURE] Allow for dependency management tools to be configured using environment variables

### ISSUE THREAD

**Issue by jpm63** [sonatype-nexus-community/vscode-iq-plugin#191]
* **What are you trying to do?**
Use the plugin to scan dependencies for a Go project which pulls dependencies via a private module repository that requires authentication. In order to prevent storing credentials to this module repository on disk, the credentials and hostname of the module repository are stored in GOPROXY environment variable, which the Go toolchain natively supports.

* **What feature or behavior is this required for?**
My use case is Go dependency scanning, but this probably affects any other toolchain that allows configuration to be set using environment variables.

* **How could we solve this issue? (Not knowing is okay!)**
One option is to map all existing process environment variables when exec'ing out to subcommands. It will be on the user to ensure the VS Code process has appropriate environment variables configured, but I think it's a fair assumption that anyone configuring their toolchains in this manner likely has that problem solved.

* **Anything else?**

cc @bhamail / @DarthHater

**Comment by DarthHater** [comment]
@jpm63 is this solved by your PR #192 ?

**Comment by jpm63** [comment]
Yes, things look great on my end.
