### ISSUE TITLE
Error building/launching plugin after React changes

### ISSUE THREAD

**Issue by gpjacobs** [sonatype-nexus-community/vscode-iq-plugin#23]
Hello,

I (forked and) cloned the latest code from master and received the following error if I try to run Launch Extension:

`Activating extension ``cameronsonatype.vscode-iq-plugin`` failed: Cannot find module 'c:\code\vscode-iq-plugin-master\build\ext-src\extension.js' 
extensionHostProcess.js:497
Here is the error stack: Error: Cannot find module 'c:\code\vscode-iq-plugin-master\build\ext-src\extension.js'`

After checking the build\ directory, that file was indeed missing so it looks like the build step that transpiles the extension.ts into extension.js wasn't being performed.

It appears that with the latest change to React (commit 2f4e1f8baa5c99faf2a03abdd165c3670ba2b0b5) the build was also switched to using yarn, so I tried just running 
`yarn start` and/or `yarn build` and received this error: 

`C:/code/vscode-iq-plugin-master/node_modules/@types/victory/index.d.ts
(75,43): Generic type 'ReactElement<P>' requires 1 type argument(s).`

Reverting to the previous version (commit 6dc93ab932663b11406f9623c0fdb7d49283610c) works fine (the extension launches without any issues).

Are there any additional steps I'm missing that are necessary to build/run the latest version of the extension?

I'm using:

-  VS Code 1.38.0
-  Typescript 3.6.2
-  yarn 1.17.3
-  npm 6.9.0

Thanks!

**Comment by adrianpowell** [comment]
My build process is to start VS Code normally and then run `npm run-script build` in the `vscode-iq-plugin` folder. When it completes, I run the plugin with `F5`. I'm using a similar setup to yours except npm version 6.4.1, and windows 10.

I have not seen this exact issue though I did find similar problems when I tried to install bootstrap and other packages. I'm not sure of the root cause, but I am investigating removing the victory dependency entirely which might help.

**Comment by adrianpowell** [comment]
I removed victory charts, so try to pull & retry.

If that doesn't work, delete `node_modules`, run `npm install` and then `npm run-script build`. We've tested it on windows and Mac and can't replicate your initial issue, so we're just guessing here. Hope it helps.

**Comment by gpjacobs** [comment]
Sounds good, I'll give that a shot. Thanks for the prompt reply!

**Comment by gpjacobs** [comment]
Pulling in the latest, then running run `npm install` and then `npm run-script build` worked, I'll close this issue. Thanks again!
