### ISSUE TITLE
[BUG] Grey text hard to read

### ISSUE THREAD

**Issue by f5oto** [sonatype-nexus-community/vscode-iq-plugin#231]
**Describe the bug**
When viewing results in VSCode, the componoent info panel uses grey text on a white background.

**To Reproduce**

1. Install Sonatype IQ plugin and view results for a Java project
2. Select a policy violation.
3. View results under "Component Info" and "Licensing" tabs

**Expected behaviour**
Change text to a darker colour

**Screenshots**
![image](https://user-images.githubusercontent.com/51363621/156791640-1361f4f4-a40a-4730-96f7-eb1006095b19.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - NodeJS Version: 14.16.0
 - VS Code Version: 1.65
 - Version of Extension 1.2.3

**Additional context**

cc @bhamail / @DarthHater

**Comment by madpah** [comment]
This has been resolved in release `1.3.0` @f5oto .
