### ISSUE TITLE
Async scan

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/vscode-iq-plugin#3]
The scan at the moment is a full application scan and takes along time on large NPM projects. e.g. test with Juice Shop https://github.com/bkimminich/juice-shop
Now a good solution is to make the scan async like it is in the Eclipse IDE plugin. Where as the results come back for each component they appear in the data grid. This would be more responsive and the user would see what is going on. Better UX.

**Comment by ButterB0wl** [comment]
@ctownshend test out master now, performance for npm and other large projects has improved significantly.  closing this out
