### ISSUE TITLE
Prevent package-lock.json from getting renamed to npm-shrinkwrap.json

### ISSUE THREAD

**Issue by roger-lau** [sonatype-nexus-community/vscode-iq-plugin#32]
When the plugin executes npm shrinkwrap, the package-lock.json file in the project is renamed to npm-shrinkwrap.json. That causes inconveniences to our build pipeline.
In your future release, would you consider keeping the package-lock.json file?

The preferred behaviour of the plugin would be not changing the original files in my project.

**Comment by DarthHater** [comment]
@roger-lau as of 0.4.0 (and working best in 0.4.4), we now can scan either npm shrinkwrap, npm package-lock or yarn lock files.

**Comment by roger-lau** [comment]
Thanks, Jeffry.
2019年12月10日 12:30 +0800、Jeffry Hesse <notifications@github.com>のメール:
