### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/vscode-iq-plugin#37]
Requirements.txt only has name and version and does not have the Extension or  Qualifier
Extension is a required field in the RestAPI call. So we need some way to get around this gap. Perhaps use the PackageURL co-cordinates

**Comment by DarthHater** [comment]
Python support is currently working for OSS Index, so this is more or less just to fix the IQ implementation.

**Comment by DarthHater** [comment]
I more or less quasi fixed this in 25eed9d9dfd03b74b919ba17e90154512e973b83 , I set the extension fairly broadly to "tar.gz", as I had tried "whl" and got zero results back. It's a bit nuclear, but it works for me so far locally. I imagine there is a better long term fix, so I'll leave this open!

**Comment by ButterB0wl** [comment]
fixed in #145
