### ISSUE TITLE
Notification to user as scan is running for long running scan

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/vscode-iq-plugin#47]
Notification to user as scan is running for long running scan. e.g. test with massive project like JuiceShop -  git clone https://github.com/bkimminich/juice-shop.git
Then wait for evaluation, could take many minutes. So I want to notify the user that it is still thinking and processing.

**Comment by DarthHater** [comment]
Yeah, we definitely need to do this. It's pretty bad that we provide no feedback currently. Does anyone know how to show a loader in the VS Code panel, or something akin? Not my wheelhouse quite yet.

**Comment by ctownshend** [comment]
Done in release 0.6.0. Now has a progress bar.
