### ISSUE TITLE
Add instrumentation for better logging and debugging and support

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/vscode-iq-plugin#71]
Add instrumentation for better logging and debugging and support

**Comment by DarthHater** [comment]
What's the kinda atypical type of logging, etc... done for VS Code extensions? Like should we start logging to a file so someone can attach that?

**Comment by ctownshend** [comment]
Yes I think we should at least provide that capability to log to a file, they can send to an issue.  A lot of issues are related to shelling out to npm commands, so anyway we can catch that and then the user can probably help themselves anyways. We are currently swallowing errors so they don't know where to look

**Comment by hboutemy** [comment]
https://stackoverflow.com/questions/44188262/where-are-the-vscode-error-logs-for-extensions

**Comment by hboutemy** [comment]
donen in #152
