### ISSUE TITLE
Alternative sort term

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/vscode-iq-plugin#74]
* Sort ascending by name
* Sort descending by name
* Sort ascending by policy
* Sort descending by policy

**Comment by DarthHater** [comment]
Is it possible to just make the current sort buttons context sensitive (so if we sort by ascending name, can we show a sort by descending button)? I haven't gotten that far in to the code around this stuff, figured I'd ask!

**Comment by ctownshend** [comment]
Hi Jeffry so I wrote this to have 4 buttons. I could not work out how to change the buttons to be context sensitive. It appears that the buttons are set in the manifest and can not be changed in the panel programmatically. Anyway, I pushed up another change to use 2 buttons and toggle between asc/desc. Also have defaulted to sorting policy descending
