### ISSUE TITLE
Path issues on Windows

### ISSUE THREAD

**Issue by gpjacobs** [sonatype-nexus-community/vscode-iq-plugin#83]
I'd like to suggest changing the method for determining the workspace root (https://github.com/sonatype-nexus-community/vscode-iq-plugin/blob/1f568ce804aad1fe9c88e3b8232a6881f2d3dda3/ext-src/packages/PackageDependenciesHelper.ts#L42)

to 

`    return workspaceRoot[0].uri.fsPath;
`

The change being a switch from _path_ to _fsPath_, the reason being that fsPath "Will handle UNC paths and normalize windows drive letters to lower-case. Also uses the platform specific path separator. "

I'm seeing issues on my Windows machine where with the current _path_ approach, the path separators are not working correctly and getWorkspaceRoot() always returns false.

I can submit a PR, but don't have a Mac and/or Linux machine to confirm that fsPath behaves correctly on those systems as well.

**Comment by DarthHater** [comment]
Send a PR bud!

**Comment by veccsolutions** [comment]
When can the PR be merged in? It's not working on my Windows unless I put in the same fix.

**Comment by DarthHater** [comment]
Hmmmm, lemme take a gander!

**Comment by ButterB0wl** [comment]
@DarthHater can you merge this?  customer needs it :)
