### ISSUE TITLE
Error when parsing pom.xml with omitted for duplicate

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/vscode-iq-plugin#85]
Some pom entries have a note added to them in the dependency_tree.txt file.

The left bracket is causing an error in the parsing of the file. Need to remove the brackets and "omitted for duplicate" from the component identification list

|  |     \- (org.jboss.xnio:xnio-api:jar:3.3.8.Final:runtime - omitted for duplicate)

![image](https://user-images.githubusercontent.com/155307/75622042-16bd3a00-5bf0-11ea-86b2-92875fece850.png)

**Comment by ButterB0wl** [comment]
![image](https://user-images.githubusercontent.com/37317224/104642390-d5ebd980-5678-11eb-8858-f80e90e2ac30.png)

still getting this on the latest version where a dupe has an open paren and doesn't resolve
