### ISSUE TITLE
Undefined Error Preventing Scan

### ISSUE THREAD

**Issue by Joech948** [sonatype-nexus-community/vscode-iq-plugin#93]
Hello,

My colleagues and I are unable to successfully scan after a successful Maven build and correct setup using sandbox-application for local scanning. We get an “undefined” error after the attempted scan takes a long time before throwing this error. After some time we began getting an error immediately after attempting a scan saying “Nexus IQ extension failure: Unable to retrieve Application ID. Could not communicate with server. Server error: 404.” We are not sure if that error is related to the previous undefined error.

**Comment by ctownshend** [comment]
At the moment the VSCode extension does not have extensive logging, this makes debugging remotely a little difficult. We are looking to add more logging code. In the meantime, could you make sure that the ApplicationId is correct, not the application name but the id in the (brackets) in IQ server. You also need to make sure that the server address is correct. I just tested a maven project and it worked. Best way to debug is to get a very small project and make sure it is not timing out. You should see the results. Anyway, that’s not to say that there couldn’t be a problem, so there could be something broken.

**Comment by michaelmworthington** [comment]
@Joech948 I tried a few things and was able to reproduce your error.

In my case, I had included a trailing slash in the IQ URL. Check your configuration for that case.

For example:
* If you go to your browser to log in at https://myiqserver.example.com/assets/index.html
* Ensure that your configuration is [https:/myiqserver.example.com](https:/myiqserver.example.com) without the trailing slash

**Comment by Joech948** [comment]
> @Joech948 I tried a few things and was able to reproduce your error.
> 
> In my case, I had included a trailing slash in the IQ URL. Check your configuration for that case.
> 
> For example:
> 
> * If you go to your browser to log in at https://myiqserver.example.com/assets/index.html
> * Ensure that your configuration is https://myiqserver.example.com without the trailing slash

Thank you Michael. This fixed the Application ID error. We are still looking into the undefined, possible timeout, issue.

**Comment by ButterB0wl** [comment]
logging was added in #145 

please open a new issue if you are still running into problems
